### ISSUE TITLE
Using the autoreload plugin hides error messages

### ISSUE THREAD

**Issue by qrest** [lightningd/plugins#108]
@renepickhardt and I are working on a new plugin and were using for this the autoreload plugin. In the new plugin we are using hooks. With the autoreload plugin active our coding errors were not visible in the lightning-cli log file. After removing it and manually loading our own plugin via `--plugin` our errors were logged in the log file.

tagging @darosior 

Edit: Just saw that this was somewhat explained in the Readme.md of the autoreload plugin. Still, this poses a problem and should be fixed.

**Comment by darosior** [comment]
@qrest is your plugin static ? Otherwise you can just use `plugin stop <yourplugin.py>` `plugin start <yourplugin.py>`

**Comment by renepickhardt** [comment]
@darosior what do you mean with static? While developing the code of our plugin is obviously changing

**Comment by darosior** [comment]
@renepickhardt I meant `static` by oposition to `dynamic` plugins. This is the default : since you don't seem to have specified it explicitly your plugin is likely dynamic.
Then you can just use [the `plugin` command](https://lightning.readthedocs.io/lightning-plugin.7.html).

**Comment by renepickhardt** [comment]
wow I was sick for way too much time and missed too many upgrades. need to think about my catching up process.

**Comment by cdecker** [comment]
Fwiw I have a patch in one of my fix PRs that'll print a huge warning if after reloading the plugin the manifest changed, urging the developer to restart c-lightning. We could later combine it to use the native stop/start support as well.
