### ISSUE TITLE
Lightning Websocket and Invoice Queue plugins

### ISSUE THREAD

**Issue by rbndg** [lightningd/plugins#119]
Hello
I've made 2 plugins and I thought I share them here. It could be useful for people.

### Redis queue for paid invoice
This is used for managing multiple nodes. When an invoice is paid the invoice id and the node pub is added to queue, so the paid invoice can be processed. (Planning to also implement "new_invoice" creation event as well)
https://github.com/rbndg/Lightning-Invoice-Queue

### C-Lightning Websocket Events
Simple WebSocket events for C-Lightning.
https://github.com/rbndg/c-lightning-events

**Comment by darosior** [comment]
Hi @rbndg, thanks for sharing! They are added in #139.

Next time, feel free to PR them directly (you can use #139) as an example.
