### ISSUE TITLE
Sauron plugin error "bad response to getchaininfo"

### ISSUE THREAD

**Issue by vincenzopalazzo** [lightningd/plugins#126]
Hi all,

I'm trying to use this plugin because I need to make a test on bitcoin testnet, I try to use Sauron plugin, but I receive the error below

`plugins/sauron/sauron.py error: bad response to getchaininfo (bad 'result' field), response was {"jsonrpc": "2.0", "id": 7, "error": {"code": -32600, "message": "Error while processing getchaininfo: Missing dependencies for SOCKS support."}}`

~~I think that the RPC method `getchaininfo` returns a wrong response inside the plugin, but I'm not sure and I want make a double-check with someone that knows already the plugin code (maybe @darosior ?) because I can make some error inside the procedure.~~

My procedure is
- clone the project && pip install requirements.
- Setting the plugin inside the file conf and remove the bitcoin conf inside it.
-  Ran the following command 
`lightningd --lightning-dir=/media/vincent/Maxtor/C-lightning/node/ --disable-plugin bcli --sauron-api-endpoint https://blockstream.info/testnet/api`

**Comment by vincenzopalazzo** [comment]
I noted that the install requirements process missed the dependence `PySocks`, but I think that this dependence is required from the dependence `requests[socks]`. I don't know how I had this error but I havr this problem on the following configuration.

- Linux Mint
- c-lightning 0.8.2.1
- Python 3.6

My solution was add the following dependence on `requirements.txt` 

`PySocks>=1.5.7`

If you think that this dependence should be included inside the requirements.txt I can open I PR because I have this solution on my branch.

Thanks for your time.

**Comment by darosior** [comment]
Sorry for getting to this so late. That's weird, pysocks should be pulled by the requests[socks] requirement.

**Comment by vincenzopalazzo** [comment]
@darosior don't worry about the delay.

I'm not comfortable with python, I'm the normal user that doesn't understand what is happening under the hood with python but I thought that you don't add this dependence because it is an indirect dependence. Maybe I'm doing something wrong with `pip3 install -r .. `command? I testd this on a different machine and I have the same result

**Comment by darosior** [comment]
Thanks for testing. Trying to reproduce now

**Comment by darosior** [comment]
Ok, so the previous requests requirement was creating the mess... So much esoterism i posted a stackoverflow answer :laughing: https://stackoverflow.com/a/63505984/12967587

**Comment by vincenzopalazzo** [comment]
@darosior Upvote and thanks to fix this
