### ISSUE TITLE
Noise plugin -1 as last_id not working

### ISSUE THREAD

**Issue by Fonta1n3** [lightningd/plugins#136]
As per the readme, to get the last received message use:
`recvmsg -1` however it fails with:
`cli/lightning-cli: -1: unrecognized option`

**Comment by Fonta1n3** [comment]
Is there anyway an optional param can be added to fetch all received messages? Currently it is a bit funky to work with this as the receiver can have no way of knowing which index to fetch bc a sender can send as many messages as they want. Would be really nice to have this feature to make it a bit more practical to use.

**Comment by cdecker** [comment]
Yep, I can think of a couple solutions:

 - tell the caller how many messages we have as part of retrieving any message. Downside is that if there is no message yet, any call will block indefinitely
 - Add a separate call that returns metadata about the messages we store, how many messages we sent, etc. Downside is that while iterating through the messages more might come in, so you'd have to re-poll after finishing the iteration.
 - Add a separate call that just returns all the messages we currently have. Downside is that the response might get huge with time.

Do you have any other ideas, or which one is preferable to you?

**Comment by Fonta1n3** [comment]
@cdecker I think the first option would be great and fit nicely with what is already available, can just abort the command if it doesn’t return anything. Thanks!

**Comment by cdecker** [comment]
Ok, added that new entry to the response. We can add the others if/when desired later.
