### ISSUE TITLE
Let autopilot adjust routing fees

### ISSUE THREAD

**Issue by renepickhardt** [lightningd/plugins#16]
In this stack exchange question https://bitcoin.stackexchange.com/questions/87488/why-is-my-lighting-node-not-routing-any-transaction/87490#87490 a lnd user assumed that the lnd autopilot would also automatically set the best routing fees.

As I wanted to change the centrality measure of lib_autopilot.py anyway to be estimated on the fee graph. While doing this the autopilot plugin could adjust/suggest the fees for each channel. 

Actually it could also be a separate plugin.

**Comment by m-schmoock** [comment]
Hey Rene, I was also thinking about this. It should be a standalone Plugin, because it is useful without autopilot and also the autopilot should not become too monolithic.

**Comment by ca-ruz** [comment]
@chrisguida This plugin has been archived.

**Comment by chrisguida** [comment]
Thanks @ca-ruz !

Closing due to plugin being archived.
