### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by thijstriemstra** [lightningd/plugins#2]
Would be nice to have a setup.py for each plugin, so dependencies can be listed there. I see unspecified dependencies now (sqlalchemy etc) and it's not clear which ones are required.

**Comment by cdecker** [comment]
Excellent idea, would a `setup.py` per plugin work? I was planning on adding a `requirements.txt` file per plugin anyway.

If we go for a `setup.py` file at the top-level of the repo we limit ourselves to python plugins which I'd like to avoid and we'd be installing all plugins and a superset of the desired plugin's dependencies if only a few plugins are desired.

**Comment by thijstriemstra** [comment]
setup.py for each plugin is ok. instead of adding requiremenmts.txt, list deps in setup.py instead.
