### ISSUE TITLE
probe: use postgres instead of sqlite when enabled

### ISSUE THREAD

**Issue by 3nprob** [lightningd/plugins#219]
If clightning is already configured to use a postgres database, it would be great to create a table there, that rather than creating a new sqlite3 database on disk

Especially for setups where the datadir for clightning is on a network-attached volume/disributed filesystem, as sqlite is known to be prone to corruption in those scenarios

**Comment by cdecker** [comment]
Adding postgresql support, or really any db supported by sqlalchemy should be very easy. I'd add a `--probe-db` option to allow operators to specify where to store the results, rather than hijacking the existing `--wallet` option, since that might be unexpected.

Very good suggestion 👍

**Comment by ca-ruz** [comment]
@chrisguida This plugin has been archived.

**Comment by chrisguida** [comment]
Thanks @ca-ruz !

Closing due to `probe` being archived.
