### ISSUE TITLE
Pilot, but not auto

### ISSUE THREAD

**Issue by carboncls** [lightningd/plugins#242]
Let autopilot make a list of suggested channels without automatically braodcasting funding tx. That way, users can get an idea of what autopilot would do and select from the list based on personal preference, current ideas on optimal network etc ...
It could be an option when starting the plugin.

**Comment by ca-ruz** [comment]
@chrisguida This plugin has been archived.

**Comment by chrisguida** [comment]
Thanks @ca-ruz !

Closing due to `autopilot` being archived.
