### ISSUE TITLE
backup plugin: "Click will abort further execution because Python 3 was configured to use ASCII"

### ISSUE THREAD

**Issue by v4w5gse65g874** [lightningd/plugins#285]
Hi there, I've initiated my channel backup using backup-cli via command line successfully, and the sqlite3 file is now seen on my sshfs mounted server.

System:
Linux ubuntu 4.15.0-140-generic
lightningd version 0.10.1
plugins repo commit 1f6f701
Python 3.6.9

When restarting lightning after adding my plugin symlink, I'm greeted with:

```
2021-08-13T03:15:15.680Z DEBUG   plugin-manager: started(12746) /root/.lightning/plugins/backup/backup-cli
Traceback (most recent call last):
  File "/root/.lightning/plugins/backup/backup-cli", line 100, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/root/.local/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

I've followed this url:
https://click.palletsprojects.com/en/7.x/python3/

I've confirmed my system supports C.UTF-8 as well as en_US.UTF-8:

root@ubuntu:~# locale -a
C
C.UTF-8
...
en_US.utf8

I've tried both exporting via command line and adding to my bashrc file C.UTF-8 and en_US.UTF-8 then sourcing the file but the same error keeps cropping up. Not sure where to go from here, much appreciate any guidance.

**Comment by v4w5gse65g874** [comment]
Hm maybe that's just backup-cli not working on startup? Backup seems to be working. I see the sqlite3 backup size changing in relation to my local version. Maybe this isn't actually an issue?

**Comment by v4w5gse65g874** [comment]
Ugh yeah this seems to be working:
```
2021-08-13T03:31:48.071Z INFO    plugin-backup.py: root        : Comparing backup version 302288 versus first write version 302289
2021-08-13T03:31:48.071Z INFO    plugin-backup.py: Comparing backup version 302288 versus first write version 302289
2021-08-13T03:31:48.072Z INFO    plugin-backup.py: root        : Versions match up
2021-08-13T03:31:48.072Z INFO    plugin-backup.py: Versions match up
```

Closing the issue.

**Comment by SimonVrouwe** [comment]
@v4w5gse65g874 Did your symlink point to a directory maybe? Be careful with that, according to [doc](https://github.com/lightningd/plugins#automatic-plugin-initialization)

> you can copy or symlink all plugin directories into your ~/.lightning/plugins directory. The daemon will load each executable it finds in sub-directories as a plugin.

and `backup.cli` is executable, but should not start as plugin.

**Comment by v4w5gse65g874** [comment]
@SimonVrouwe hm, ok ... this is how i'm doing it:
```
root@ubuntu:~# ll ~/.lightning/plugins/
total 8
drwxr-xr-x 2 root root 4096 Aug 12 22:42 ./
drwx------ 4 root root 4096 Jul  9 21:27 ../
lrwxrwxrwx 1 root root   26 Aug 12 22:42 backup -> /root/repos/plugins/backup/
lrwxrwxrwx 1 root root   29 Jul  9 21:30 rebalance -> /root/repos/plugins/rebalance/
```
