### ISSUE TITLE
Cannot Rebalance without msatoshi argument

### ISSUE THREAD

**Issue by agnjkafgh** [lightningd/plugins#29]
I would like to rebalance my channels 50/50 which should work if I do not provide the `msatoshi` argument. Looks like msatoshi should be a whole number and not have a decimal point.
```
"Error while processing rebalance: 
RpcError('RPC call failed: method: invoice, payload: 
{
\\'msatoshi\\' : 8388607500.0msat, 
\\'label\\': \\'Rebalance-23a20dc6-356f-423e-8a0c-6a835a061847\\', 
\\'description\\ ': \\'1516934x52x0 to 1517537x39x0\\', 
\\'expiry\\': 120
}, 
error: {
\\'code\\': -32602, 
\\'message\\': \ "\\'msatoshi\\' should be millisatoshis or \\'any\\', not \\'8388607500.0msat\\'\"
}',)"

```

**Comment by m-schmoock** [comment]
@agnjkafgh did the error occur when not supplying a msat amount and let the plugin do the math? Or did you try to balance `8388607500.0msat`, because there is obviously no sub-millisatoshi...

**Comment by agnjkafgh** [comment]
Yup. I submitted two channels which have 16777215 sats each and the plugin did the math correctly. I believe the plugin attempted to create an invoice with the **8388607500.0msat** in the `msatoshi` field and it failed. If I am not mistaken if the plugin created an invoice with  8388607500msat instead it should have worked.

**Comment by m-schmoock** [comment]
Thx. Can you also supply logs ? I never had this...

**Comment by agnjkafgh** [comment]
`cli/lightning-cli rebalance 1516934x52x0 1517537x39x0`
```
"Error while processing rebalance: 
RpcError('RPC call failed: method: invoice, payload: 
{
\\'msatoshi\\' : 8388607500.0msat, 
\\'label\\': \\'Rebalance-23a20dc6-356f-423e-8a0c-6a835a061847\\', 
\\'description\\ ': \\'1516934x52x0 to 1517537x39x0\\', 
\\'expiry\\': 120
}, 
error: {
\\'code\\': -32602, 
\\'message\\': \ "\\'msatoshi\\' should be millisatoshis or \\'any\\', not \\'8388607500.0msat\\'\"
}',)"
```

**Comment by m-schmoock** [comment]
I meant the logfile... Not cmd output

**Comment by m-schmoock** [comment]
Nvm, have it. Thx. will fix quickly...

**Comment by m-schmoock** [comment]
@agnjkafgh which pylightning Version are you using?

**Comment by m-schmoock** [comment]
@agnjkafgh Can you test if this fix helps? https://github.com/lightningd/plugins/pull/30

I think it is cause by an outdated pylightning version, but not sure since I cant reproduce this.

**Comment by agnjkafgh** [comment]
Yup this works perfectly!

**Comment by m-schmoock** [comment]
Thanks. I will include this in a bigger cleanup/refinment PR im working on.
