### ISSUE TITLE
Fee adjust settings

### ISSUE THREAD

**Issue by Coinomatron** [lightningd/plugins#327]
Hi, is there a way to change the built in parameters for the fee adjust? I've noticed it changes the empty channels to a much higher fee than I'd like. Adjusting it manually now. Thanks.

**Comment by AutonomousOrganization** [comment]
Hi, the feeadjuster [plugin](https://github.com/lightningd/plugins/tree/master/feeadjuster) looks at the ratio of the channel to set fees. You can change the overall parameters in your lightning config like this: 
```
fee-base=0
fee-per-satoshi=13
```

**Comment by Coinomatron** [comment]
The thing is, that even with low fee-per-sat in the config, the auto adjust sets the preferred direction fees so high, I'm kind of paranoid that the network will discard my node entirely. Anyway, thanks, I'll play with it a bit more.

**Comment by Coinomatron** [comment]
Small follow up if someone is curious about the same thing, in the rebalance.py at the bottom, you can adjust certain parameters such as setting the rebalance algo on 'soft'.
