### ISSUE TITLE
Commando is unable to send commands with multiple fields.

### ISSUE THREAD

**Issue by PestToast** [lightningd/plugins#334]
I have tried everything from `l1-cli commando $L2ID sendmsg $L3ID "$MESSAGE"` to `l1-cli commando $L2ID pay $INVOICE` and they just hang with no error or stdout.

At first I thought maybe it was external plugins that couldn't be run, but a single command plugin like `summary` works fine.

I was going to try to see if I could figure out what the issue was myself, but I don't know how to get a more verbose output. Maybe that's something I missed in the manpages, but I've hit an impasse.

**Comment by cmdruid** [comment]
Have you checked the log output for lightningd?

**Comment by vincenzopalazzo** [comment]
commando is now deprecated so you should use the core lightning commando implementation
