### ISSUE TITLE
commando-reader=<id>: unrecognized option (is commando_reader)

### ISSUE THREAD

**Issue by jsarenik** [lightningd/plugins#343]
No matter if used as a command-line parameter with `--commando-reader=<id>` or in config file as `commando-reader=<id>`

The option which works is `commando_reader` in the config file and `--commando_reader` in command line of `lightningd`.

So no dash, but underscore. Will do a PR for the readme in a moment.

**Comment by laanwj** [comment]
Yes looks like it's wrong in the plugin: https://github.com/lightningd/plugins/blob/master/commando/commando.py#L418

In other plugins, the argument definitions use `-` e.g. https://github.com/lightningd/plugins/blob/master/donations/donations.py#L191

I think simply search-and-replacing the snake_case with kebab-case spelling throughout the implementation files will do it.
