### ISSUE TITLE
Rebalance seems broken

### ISSUE THREAD

**Issue by Coinomatron** [lightningd/plugins#374]
Not sure what's going on, when started, it's not adjusting to manually input feeratio's, it doesn't rebalance at all and just spits out tons of the same routing lines in the debug log. Also not rebalancing between specific channels, no matter the feeratio. Perhaps network topology has changed along with how the rebalance script works, but would like to hear feedback on the matter. Running latest repo build for lightningd.

**Comment by svpi11** [comment]
I have the same kind of results. Any explanation ? My node is well connected and 10+channels
