### ISSUE TITLE
Node crashes after fundchannel and execution of listchannels cmd

### ISSUE THREAD

**Issue by sunnyokoroawa** [lightningd/plugins#428]
I successfully funded a channel, my 1st and only channel.

I executed the listfunds to see the balance after which I ran the listchannels cmd.

Immediately i ran the listchannels cmd, mt node froze, no cmd could be executed, even cli cmd to stop ln.

I had to force-stop it using the CTRL C cmd and noticed the error as attached.

The issue is mainly with the listchannel cmds, immediately it is executed, it stops the node.
![Listchannel is crashing the node](https://user-images.githubusercontent.com/79402939/220355804-195ba0b4-e0ab-4340-b326-8f32a5ca0e9e.PNG)

![Listchannel fails  again](https://user-images.githubusercontent.com/79402939/220357503-87f78ad2-5ae3-4765-a661-e502f0942edc.PNG)

![Fatal Error](https://user-images.githubusercontent.com/79402939/220354733-04fac111-caeb-4467-9928-bec6ee1c9fe1.PNG)

**Comment by sunnyokoroawa** [comment]
It is not just when you run the listchannels cmd, it can happen even when you are not interacting with the cli.

I just experienced that now

![image](https://user-images.githubusercontent.com/79402939/220378581-17f7aaf5-fe20-4751-90e0-f6c684ad4426.png)

**Comment by sunnyokoroawa** [comment]
send_backtrace
        common/daemon.c:33
0x7f5915bd8ffe crashdump
        common/daemon.c:46
0x7f591596251f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x7f59159b6a7c __pthread_kill_implementation
        ./nptl/pthread_kill.c:44
0x7f59159b6a7c __pthread_kill_internal
        ./nptl/pthread_kill.c:78
0x7f59159b6a7c __GI___pthread_kill
        ./nptl/pthread_kill.c:89
0x7f5915962475 __GI_raise
        ../sysdeps/posix/raise.c:26
0x7f59159487f2 __GI_abort
        ./stdlib/abort.c:79
0x7f5915c80669 call_error
        ccan/ccan/tal/tal.c:93
0x7f5915c80704 check_bounds
        ccan/ccan/tal/tal.c:165
0x7f5915c80735 to_tal_hdr
        ccan/ccan/tal/tal.c:175
0x7f5915c80775 to_tal_hdr_or_null
        ccan/ccan/tal/tal.c:186
0x7f5915c8150d tal_bytelen
        ccan/ccan/tal/tal.c:637
0x7f5915bdc044 do_enqueue
        common/msg_queue.c:22
0x7f5915bdc12c msg_enqueue
        common/msg_queue.c:37
0x7f5915bd93db daemon_conn_send
        common/daemon_conn.c:161
0x7f5915bd26d1 handle_gossip_in
        connectd/multiplex.c:665
0x7f5915bd31b5 handle_message_locally
        connectd/multiplex.c:764
0x7f5915bd3239 read_body_from_peer_done
        connectd/multiplex.c:1104
0x7f5915c7b535 next_plan
        ccan/ccan/io/io.c:59
0x7f5915c7ba10 do_plan
        ccan/ccan/io/io.c:407
0x7f5915c7baad io_ready
        ccan/ccan/io/io.c:417
0x7f5915c7ccf5 io_loop
        ccan/ccan/io/poll.c:453
0x7f5915bcff06 main
        connectd/connectd.c:2053
0x7f5915949d8f __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7f5915949e3f __libc_start_main_impl
        ../csu/libc-start.c:392
0x7f5915bc8814 ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightning_connectd: FATAL SIGNAL (version v22.11.1)
0x7f5915bd8f67 send_backtrace
        common/daemon.c:33
0x7f5915be255e status_failed
        common/status.c:221
0x7f5915be2670 status_backtrace_exit
        common/subdaemon.c:18
0x7f5915bd9004 crashdump
        common/daemon.c:49
0x7f591596251f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x7f59159b6a7c __pthread_kill_implementation
        ./nptl/pthread_kill.c:44
0x7f59159b6a7c __pthread_kill_internal
        ./nptl/pthread_kill.c:78
0x7f59159b6a7c __GI___pthread_kill
        ./nptl/pthread_kill.c:89
0x7f5915962475 __GI_raise
        ../sysdeps/posix/raise.c:26
0x7f59159487f2 __GI_abort
        ./stdlib/abort.c:79
0x7f5915c80669 call_error
        ccan/ccan/tal/tal.c:93
0x7f5915c80704 check_bounds
        ccan/ccan/tal/tal.c:165
0x7f5915c80735 to_tal_hdr
        ccan/ccan/tal/tal.c:175
0x7f5915c80775 to_tal_hdr_or_null
        ccan/ccan/tal/tal.c:186
0x7f5915c8150d tal_bytelen
        ccan/ccan/tal/tal.c:637
0x7f5915bdc044 do_enqueue
        common/msg_queue.c:22
0x7f5915bdc12c msg_enqueue
        common/msg_queue.c:37
0x7f5915bd93db daemon_conn_send
        common/daemon_conn.c:161
0x7f5915bd26d1 handle_gossip_in
        connectd/multiplex.c:665
0x7f5915bd31b5 handle_message_locally
        connectd/multiplex.c:764
0x7f5915bd3239 read_body_from_peer_done
        connectd/multiplex.c:1104
0x7f5915c7b535 next_plan
        ccan/ccan/io/io.c:59
0x7f5915c7ba10 do_plan
        ccan/ccan/io/io.c:407
0x7f5915c7baad io_ready
        ccan/ccan/io/io.c:417
0x7f5915c7ccf5 io_loop
        ccan/ccan/io/poll.c:453
0x7f5915bcff06 main
        connectd/connectd.c:2053
0x7f5915949d8f __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7f5915949e3f __libc_start_main_impl
        ../csu/libc-start.c:392
0x7f5915bc8814 ???
        ???:0
0xffffffffffffffff ???
        ???:0

**Comment by vincenzopalazzo** [comment]
Sorry for the delay here, can you move this issue to the core lightning repository? maybe without photos but just plain text?

Thanks!

>Immediately i ran the listchannels cmd, mt node froze, no cmd could be executed, even cli cmd to stop ln.

while the cli is stuck what is the status of the process? in other words if you run `htop`  on your terminal can what kind of activity related to lightning you see?

Please also attach this info when you open the issue on the core lightning repository.

I'm closing this here because it is unrelated to plugins
