### ISSUE TITLE
feeadjuster: feeadjuster-median-multiplier option is not recognized

### ISSUE THREAD

**Issue by dazl** [lightningd/plugins#445]
Core Lightning v23.02.2 fails to start and logs:

`feeadjuster-median-multiplier=0.8: unrecognized option`

(context: other options are picked up as expected i.e.

```
feeadjuster-feestrategy=median
feeadjuster-max-htlc-steps=1
```
)

**Comment by chrisguida** [comment]
This version CLN is no longer supported.
