### ISSUE TITLE
git clone not working for the rebalance repo?

### ISSUE THREAD

**Issue by Fonta1n3** [lightningd/plugins#477]
I am sure I used to be able to `git clone https://github.com/lightningd/plugins/tree/master/rebalance`, now it returns an error `fatal: repository 'https://github.com/lightningd/plugins/tree/master/rebalance/' not found`. Pretty tedious to have to copy the files manually... What am I doing wrong?

**Comment by chrisguida** [comment]
I can't reproduce this... can you try again with latest master and let me know if it's still happening?
