### ISSUE TITLE
[feat]: Display failing / non-tested plugins in a matrix with dynamic badges instead of moving to archive

### ISSUE THREAD

**Issue by chrisguida** [lightningd/plugins#494]
Research whether it's possible to add some columns to the current "available plugins" list, where one column is "passing CI" and the other is "has tests", and dynamically update these for each plugin so users can quickly determine the state of each plugin's maintenance at a glance.

If they're failing CI we obviously need a way to remove them from testing so other plugins can use the CI.

cdecker says:

>I wonder if we can trick the badge generators into treating each plugin as a separate branch or tag

**Comment by chrisguida** [comment]
Part of this is done in #509 

We should decide what we want to do with failing plugins.

Currently we archive them after a short time because they cause the CI job to fail.

But we could remove the CI job failure and simply allow them to display a red failure badge.

I'm partial to keeping it how it is now, but I'm not sure which is best.

Perhaps we should add a few more prior versions of CLN to the CI (and remove some Python versions) and let plugins fail for a bit longer before we count them as archived?

@cdecker @vincenzopalazzo @m-schmoock @daywalker90 @sip-21 thoughts?

**Comment by daywalker90** [comment]
This is what we probably want: CI only fails if a plugin goes from previously passing->failing. If it was already failing, CI passes. In this way we get alerted once and then CI is chill again.

I agree we should test more cln versions and add them to the table. If a plugin is failing the last x versions it gets archived. In this way users running older cln versions can get value from the plugins repo aswell.

**Comment by chrisguida** [comment]
Hmm that definitely sounds useful, I wonder how difficult it would be to implement, do you want to take a crack at it?

>I agree we should test more cln versions and add them to the table. If a plugin is failing the last x versions it gets archived. In this way users running older cln versions can get value from the plugins repo aswell.

Cool, I'll add another version or two
