### ISSUE TITLE
sauron: fix fee response or deprecate the plugin

### ISSUE THREAD

**Issue by vincenzopalazzo** [lightningd/plugins#508]
In the next release, there is a cleanup that breaks sauron and I think trusted coin, so we should consider fixing it or archiving.

Related commit: https://github.com/ElementsProject/lightning/pull/7094/commits/82c1d8b547f3a07780654d8ac5861c36cf774e0c

P.S: a modern alternative of this is Folgore https://github.com/coffee-tools/folgore if we ran out of alternative backend

**Comment by vincenzopalazzo** [comment]
Duplicated https://github.com/lightningd/plugins/issues/458

**Comment by chrisguida** [comment]
@vincenzopalazzo is folgore a plugin? should we add it in here?

**Comment by chrisguida** [comment]
If it's a plugin, I say we add it here! This should be a collection of all useful, actively maintained plugins.
