### ISSUE TITLE
REST API Plugin 

### ISSUE THREAD

**Issue by dfresh613** [lightningd/plugins#51]
I have the need to access and administer my Lightning Node remotely in a secure, and authenticated manner (possibly with multi-user and some rbac).

I was unable to find any existing repositories which provided a robust REST API. And certainly none that are c-lightning plugins.

So i started one:

https://github.com/dfresh613/C-Lightning-REST

My goal is to support a large subset of methods available to the LightningRPC class of PyLightning so they will also be executable through a REST api with authentication and TLS. 

I hope to have it ready to be a plugin within the next 2 weeks or so. I was just wondering if there was already anything else like this out there, or any explicit reason why we wouldn't want a REST API on c-lightning?

**Comment by fiatjaf** [comment]
[Spark](https://github.com/shesek/spark-wallet) is a widely-deployed wallet interface to c-lightning that exposes a `POST /rpc` endpoint which gives access to all c-lightning RPC methods. If you have one running you can just reuse its key (start the Spark server with `-k` to get the key).

[Sparko](https://github.com/fiatjaf/sparko) is a rewrite of that that is deployed easily with a single binary you just place on top of your c-lightning node. It exposes the same `POST /rpc` endpoint, and it also supports custom keys with fine-grained method access permissions. It also allows access to custom methods provided by plugins.
