### ISSUE TITLE
helpme: returns `list assignment index out of range`

### ISSUE THREAD

**Issue by jb55** [lightningd/plugins#59]
When I try to run `helpme:` "Error while processing helpme: IndexError('list assignment index out of range')"

**Comment by theStack** [comment]
Do you have a line in your configfile without assignment (`=`)? Then the linked PR https://github.com/lightningd/plugins/pull/106 probably fixes this.

**Comment by jb55** [comment]
yes my config file is:

```
mainnet
log-level=debug
alias=@jb55
rgb=ff0000
```
