### ISSUE TITLE
Prometheus error and no data after update to lightning 0.8.0

### ISSUE THREAD

**Issue by tobg** [lightningd/plugins#80]
Everything works fine with lightning 0.7.1

After changed to lightning 0.8.0 I got the following error on prometheus.

level=warn ts=2019-12-31T15:32:39.600Z caller=scrape.go:930 component="scrape manager" scrape_pool=lightningd target=http://clightning_tobg:9900/metrics msg="append failed" err="expected equal, got \"INVALID\""

With curl I get all the metrics.

Everything runs on docker.

**Comment by cdecker** [comment]
Can you share the contents of the http://clightning_tobg:9900/metrics page? It's likely an uncaught exception while collecting the information from the RPC :-)

**Comment by tobg** [comment]
Hi Christian, this is the output from curl:

# HELP lightning_node_info Static node information
# TYPE lightning_node_info gauge
lightning_node_info{alias="TOBG-CL",color="03db7a",id="03db7ac914d745f489c5974a998c1984a7d015cb117f9c31e10f337e7df2166e58",lightning-dir="/root/.lightning/bitcoin",network="bitcoin",version="v0.8.0"} 1.0
# HELP lightning_node_blockheight Current Bitcoin blockheight on this node.
# TYPE lightning_node_blockheight gauge
lightning_node_blockheight 611099.0
# HELP lightning_funds_total Total satoshis we own on this node.
# TYPE lightning_funds_total gauge
lightning_funds_total 0.0
# HELP lightning_funds_output On-chain satoshis at our disposal
# TYPE lightning_funds_output gauge
lightning_funds_output 0.0
# HELP lightning_funds_channel Satoshis in channels.
# TYPE lightning_funds_channel gauge
lightning_funds_channel 0.0
# HELP lightning_peer_channels The number of channels with the peer
# TYPE lightning_peer_channels gauge
# HELP lightning_peer_connected Is the peer currently connected?
# TYPE lightning_peer_connected gauge
# HELP lightning_channel_htlcs How many HTLCs are currently active on this channel?
# TYPE lightning_channel_htlcs gauge
# HELP lightning_channel_capacity How many funds are in this channel in total?
# TYPE lightning_channel_capacity gauge
# HELP lightning_channel_spendable How much can we currently send over this channel?
# TYPE lightning_channel_spendable gauge
# HELP lightning_channel_balance How many funds are at our disposal?
# TYPE lightning_channel_balance gauge

**Comment by cdecker** [comment]
It appears that some of these values are not being populated correctly. Is this directly after start? Are there any exceptions being printed to the logs?
