### ISSUE TITLE
Unexpected and unexplainable error

### ISSUE THREAD

**Issue by sumBTC** [lightningd/plugins#84]
First of all: `sendinvoiceless` is a really cool and useful feature that I've implemented in my lightning [game](https://BitcoinDayTrader.nl)

I run 2 nodes like this: myshtery <-> Bitkoins.nl <-> 7 other channels

Myshtery is only connect to Bitkoins.nl. I have paid "Ship of Theseus" via Bitkoins.nl a few day ago 1000 satoshi with `sendinvioiceless` and it went ok over 4 hops and a small fee.

I had to pay "Ship of Theseus" again today but it didn't work while it's a very well connected node and it worked before. Error message:

`error: {'message': 'Sending failed'}\",)"`

I tried increasing the fee but nothing worked. I tested paying another node ID with Bitkoins.nl and that went fine.

I then decided to try to pay with myshtery but since myshtery is only connected to Bitkoins.nl it should have made it harder not easier to pay. However, the payment went smooth (via Bitkoins.nl obviously) over 6 hops and a small fee. After that I tried to pay again via Bitkoins.nl but it didn't work. Restarted Bitkoins.nl but that also didn't help.

What on Earth could cause this situation?

c-lightning: "v0.8.0-1-gb14b2b0"

**Comment by jarret** [comment]
I was having problems similar to what was described using circular payments borrowing logic from `sendinvoiceless.py` on a different project that traced back to an issue with the `cltv-final` setting.

By default, C-Lightning will only accept 10 blocks as the final hop cltv for the route back to oneself. `sendinvoiceless.py` checks that boot arg and uses that as the final routing hop cltv. However, if a block arrives during the operation (which can span a couple seconds to execute, depending), the final hop on the circular route back to itself will get rejected and the payment will fail.

After padding that `cltv-final` value on the route construction (the equivalent of `setup_routing_fees()` in `sendinvoiceless.py`) by 3 blocks, I no longer had the same intermittent failures. It looks like the script has an option to set that value for `sendinvoiceless.py` which can be greater than the default `cltv-final` boot arg.

**Comment by sumBTC** [comment]
@jarret thanks I will look into it later because I have not time now but at first sight it doesn't seem to make a difference.

**Comment by sumBTC** [comment]
@jarret Should I put (for example) `cltv-final=20` in config in .lightning?

**Comment by jarret** [comment]
hmm, both the `lightningd` boot arg option and the plugin option are both called `cltv-final`, so I am not sure which one will be adjusted as a result (and that namespace collision is probably a problem that should be fixed).

Maybe edit the script to pad on a higher value to use for `setup_routing_fees()` for now?

**Comment by sumBTC** [comment]
I changed:

`plugin.add_option('cltv-final', 10, 'Number of blocks for final CheckLockTimeVerify expiry')`

into

`plugin.add_option('cltv-final', 20, 'Number of blocks for final CheckLockTimeVerify expiry')`

in `sendinvoiceless.py` but that didn't change anything.

**Comment by darosior** [comment]
> hmm, both the lightningd boot arg option and the plugin option are both called cltv-final, so I am not sure which one will be adjusted as a result (and that namespace collision is probably a problem that should be fixed).

It is indeed. It results from the plugin option to not be set, you can inspect it with `listconfigs`.

Regarding the issue it seems related to https://github.com/ElementsProject/lightning/pull/3376.

**Comment by jarret** [comment]
> I changed:
> 
> `plugin.add_option('cltv-final', 10, 'Number of blocks for final CheckLockTimeVerify expiry')`
> 
> into
> 
> `plugin.add_option('cltv-final', 20, 'Number of blocks for final CheckLockTimeVerify expiry')`
> 

Looks like in the `init` function, it overwrites that value with whatever is obtained from the `listconfigs` rpc call, so this change isn't doing anything.

**Comment by sumBTC** [comment]
@darosior I've set it to 20 and I also see that value with `listconfigs` and it worked! I got:

`"1000000 msat delivered with 1010 msat fee over 7 hops"`

 Thanks both of you for all the help!
